baseURL = "https://mattcorritore.com"
languageCode = "en-us"
title = "Matt Corritore"
theme = "hugo-bearblog"

[params]
  description = "People analytics and data science. Writing about things I find interesting."
  author = "Matt Corritore"
  footer = "Matt Corritore · [RSS](/index.xml)"
  dateformat = "2006-01-02"
  favicon = "favicon.ico"
